# Generated by Django 4.2.13 on 2024-05-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_alter_school_name_alter_student_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='principal',
            field=models.CharField(default='Default Principal Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
