# Generated by Django 4.2.13 on 2024-05-18 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_two_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.CharField(max_length=264)),
            ],
        ),
    ]
